import assert from "assert";
import { ALU } from "../build/debug.js";
export function TestALU() {
    assert.strictEqual(ALU(0, -1, true, false, true, false, true, false), 0)
    assert.strictEqual(ALU(0, -1, true, true, true, true, true, true), 1)
    assert.strictEqual(ALU(0, -1, true, true, true, false, true, false), 65535)
    assert.strictEqual(ALU(0, -1, false, false, true, true, false, false), 0)
    assert.strictEqual(ALU(0, -1, true, true, false, false, false, false), 65535)
    assert.strictEqual(ALU(0, -1, false, false, true, true, false, true), 65535)
    assert.strictEqual(ALU(0, -1, true, true, false, false, false, true), 0)
    assert.strictEqual(ALU(0, -1, false, false, true, true, true, true), 0)
    assert.strictEqual(ALU(0, -1, true, true, false, false, true, true), 1)
    assert.strictEqual(ALU(0, -1, false, true, true, true, true, true), 1)
    assert.strictEqual(ALU(0, -1, true, true, false, true, true, true), 0)
    assert.strictEqual(ALU(0, -1, false, false, true, true, true, false), 65535)
    assert.strictEqual(ALU(0, -1, true, true, false, false, true, false), 65534)
    assert.strictEqual(ALU(0, -1, false, false, false, false, true, false), 65535)
    assert.strictEqual(ALU(0, -1, false, true, false, false, true, true), 1)
    assert.strictEqual(ALU(0, -1, false, false, false, true, true, true), 65535)
    assert.strictEqual(ALU(0, -1, false, false, false, false, false, false), 0)
    assert.strictEqual(ALU(0, -1, false, true, false, true, false, true), 65535)
    assert.strictEqual(ALU(17, 3, true, false, true, false, true, false), 0)
    assert.strictEqual(ALU(17, 3, true, true, true, true, true, true), 1)
    assert.strictEqual(ALU(17, 3, true, true, true, false, true, false), 65535)
    assert.strictEqual(ALU(17, 3, false, false, true, true, false, false), 17)
    assert.strictEqual(ALU(17, 3, true, true, false, false, false, false), 3)
    assert.strictEqual(ALU(17, 3, false, false, true, true, false, true), 65518)
    assert.strictEqual(ALU(17, 3, true, true, false, false, false, true), 65532)
    assert.strictEqual(ALU(17, 3, false, false, true, true, true, true), 65519)
    assert.strictEqual(ALU(17, 3, true, true, false, false, true, true), 65533)
    assert.strictEqual(ALU(17, 3, false, true, true, true, true, true), 18)
    assert.strictEqual(ALU(17, 3, true, true, false, true, true, true), 4)
    assert.strictEqual(ALU(17, 3, false, false, true, true, true, false), 16)
    assert.strictEqual(ALU(17, 3, true, true, false, false, true, false), 2)
    assert.strictEqual(ALU(17, 3, false, false, false, false, true, false), 20)
    assert.strictEqual(ALU(17, 3, false, true, false, false, true, true), 14)
    assert.strictEqual(ALU(17, 3, false, false, false, true, true, true), 65522)
    assert.strictEqual(ALU(17, 3, false, false, false, false, false, false), 1)
    assert.strictEqual(ALU(17, 3, false, true, false, true, false, true), 19)
    console.log("ALU test cases passed");
}