[unstable]
build-std = ['std', 'panic_abort']
build-std-features = ['panic_immediate_abort']

[build]
target = "wasm32-unknown-unknown"
rustflags = '-Ctarget-feature=+atomics,+bulk-memory,+mutable-globals'
